general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  openrouter_api_key: os.environ/OPENROUTER_API_KEY
  database_url: os.environ/DATABASE_URL

model_list:
  - model_name: phi3:latest
    litellm_params:
      model: phi3:latest
      api_base: http://100.94.136.15:11434
      api_type: ollama
      provider: ollama
      custom_llm_provider: ollama 